### ISSUE TITLE
Push the source code

### ISSUE THREAD

**Issue by weaponsb** [CDuke/AutoMerge#16]
Hi,
Please, can you push your source code on repo github ?

Thanks

**Comment by CDuke** [comment]
Hi, 
Why do you need source code?

**Comment by Manuel-S** [comment]
To implement https://github.com/CDuke/AutoMerge/issues/13 for example.

**Comment by Mikahk** [comment]
I would like to see a version for VS 2015. So please release the source. I would like to add specific features

**Comment by CDuke** [comment]
sources published

**Comment by MikChoco** [comment]
Thank you very much for the sources!
