### ISSUE TITLE
Merge renamed files -> The TFS do not merge the file, it make a branch of the file.

### ISSUE THREAD

**Issue by Mechatronix** [CDuke/AutoMerge#25]
Hi, 

i have a problem at merging changes from a renamed/moved file from main to a branch. 
The TFS do not merge the file, it make a branch of the file. 

Example:
Main/Folder/NewFolder/File.txt
Release/Folder/File.txt[merge] -> But it takes Release/Folder/NewFolder/File.txt [branch]

I can solve the problem when I change AutoMerge, so it will merge files with the function MergeByFile() by default. 

What is the reason, why AutoMerge first take the MergeToBranch() and only if their are UnexpectedFileRestored conflicts then take the MergeByFile()? 

Thanks for your replay

Mechatronix

**Comment by CDuke** [comment]
The reason for this algorithm, which identifies which folder should be merged.
It find "root" folder in changeset. For example, in your case in will be "Main/Folder/NewFolder/File.txt
Release/Folder/". But after merge, new file created at another branch, instead moved to another folder.
This leads to incorrect results.

I hope I was able to explain clearly.

**Comment by Mechatronix** [comment]
Sorry, but I don't know, what are you mean. 
What's the different with the root folder?

Details of my Example
CS1 (New) Main/Folder/File.txt 
CS2 (Move) Main/Folder/NewFolder/File.txt
CS2 (Fix) Main/Folder/NewFolder/File.txt

Release is a Branch of CS1, now I will merge CS2 to the Release Branch

The Result of MergeToBranch(CS2) is Release/Folder/NewFolder/File.txt [branch]
The Result of MergeByFile(CS2) Release/Folder/File.txt [merge] this is much better in my opinion.

Thanks for replay 

Mechatronix

**Comment by CDuke** [comment]
CS2 has root folder is  Main/Folder/NewFolder/. Release Branch (CS1) does not have this folder, that why it "branch". You can check it by standart TFS merging.

**Comment by CDuke** [comment]
Do you understand why it is not automatically switched to MergeByFile?

**Comment by Mechatronix** [comment]
I have checked this bevor, for me it’s an unhappy (buggy) function of TFS. 
So I was look for a solution, I can refactor the Main and I can fix bugs in Main and the Releases. 

Sorry but I do not really understand why AutoMerge do not switch to MergeByFile. 

`if (conflict.BaseChangeType.HasFlag(ChangeType.Undelete)
                    && !conflict.TheirChangeType.HasFlag(ChangeType.Undelete))
                {
                    return true;
                }
`
What is the reason auf Undelete a File, I found nothing.

**Comment by Mechatronix** [comment]
Is it an option to find the ChangType.Branch and then switch to MergeByFile? 

Do you use MergeByBranch because of Performance Issues of TFS?

**Comment by CDuke** [comment]
"What is the reason af Undelete a File, I found nothing." - It's was my case, when some files were moved to another folder and during the merge it recovered
"Is it an option to find the ChangType.Branch and then switch to MergeByFile?" - No
"Do you use MergeToBranch because of Performance Issues of TFS" - yes

**Comment by Mechatronix** [comment]
> "What is the reason af Undelete a File, I found nothing." - It's was my case, when some files were moved to another folder and during the merge it recovered

So we have the same Problem, right? Why does it not work for me? 
When I merge only one File it works, but if I merge a Changset with more than one file, it will not work.
>"Is it an option to find the ChangType.Branch and then switch to MergeByFile?" – No

Can we find another conclusion?

**Comment by Mechatronix** [comment]
Please help me. 
 I have done a big Refactoring with move a lot of Files to another Folder. 
Now my colleagues and I have the described problem with the merge.

Thanks a lot

**Comment by Elaskanator** [comment]
Bumping because this is wasting productivity for me at work, in a simpler case of just renaming a file (without moving its location):
[StackExchange question](https://dba.stackexchange.com/questions/209940) trying to do it with TFS Power Tools (TFPT.exe).

**Comment by Mechatronix** [comment]
We have fixed it for us.
Please see [Fork of AutoMerge](https://github.com/ZachiZachiZachi/AutoMerge/releases)
