### ISSUE TITLE
Fails to find common root , when letter casing is different

### ISSUE THREAD

**Issue by vradzius** [CDuke/AutoMerge#36]
The issue happens when more when one file is changed in the changeset and the paths returned by TFS looks like this for example:
$/BranChes/....
$/branches/...
During the common parent lookup the case sensitive comparition is done and function ```FindShareFolder``` fails to find common parent.
The changes need to be done to file BranchesViewModel.cs: 
line 532:  ```while (folder != rootFolder && !changeFolder.Contains(folder))```
and 535: ```if (folder != null && changeFolder.ToLower().Contains(folder.ToLower()))```

If you want I can file pull request for this change.

**Comment by CDuke** [comment]
pull request is good solution

**Comment by vradzius** [comment]
Thank you for great extension happy to help.
