### ISSUE TITLE
VS2019 support

### ISSUE THREAD

**Issue by stimpy77** [CDuke/AutoMerge#43]
Please port AutoMerge to VS 2019. I am a regular user of Auto Merge but keep having to use VS 2017 in order to work on our project's bug fixes just for the AutoMerge feature.

**Comment by stimpy77** [comment]
the good news is, it's doable :) I forgot to fork first before branching for a VS2019 build. 

- update the projects to .net framework 4.7.2
- uninstall the tfs libs/packages, and reinstall them using the latest preview packages
- might have to install the Microsoft.TeamFoundationServer.ExtendedClient package (I did, but not sure if there's a cleaner approach as it added a lot)
- poke and prod as such till errors go away 

I'm running AutoMerge in VS 2019 now

**Comment by CDuke** [comment]
Done - [Auto Merge for VS 2019](https://marketplace.visualstudio.com/items?itemName=KulikovDenis.AutoMergeforVisualStudio2019)
