### ISSUE TITLE
Any plans for Visual Studio 2022 ?

### ISSUE THREAD

**Issue by gjactat** [CDuke/AutoMerge#55]
Hello,

Thanks for building this extension. It saves me hours every week... TBH, I don't even understand why it is still so hard to merge TFVC changesets across branches nowadays. I know TFVC is not the future but anyway...

So, as Visual Studio 2022 is finally out, I was wondering if you had plans for Auto Merge regarding this new version.
If not, perhaps you've heard of similar tools/extensions that could help us in the process of merging change sets in the future.

Thank you for your attention,
Guillaume

**Comment by ihcaesar** [comment]
Added VS 2022 support in [https://github.com/ihcaesar/AutoMerge](url)

**Comment by gjactat** [comment]
The fork provided by @ihcaesar  seems OK in Visual Studio 2022.

**Comment by aalexr** [comment]
@ihcaesar Could you please make another pull request just for VS 2022 and branches not found? Preferable per each feature. Already existing PR contains also some other changes about case sensitivity that I can’t immediately review whereas these look straight forward.

P.S. Denis is very busy right now, so I ask him if I can take over :) I will try to contribute to AutoMerge in my spare time.

**Comment by ihcaesar** [comment]
@aalexr Splitted my changes into two pull requests. However, I've combined the case sensitivity changes and the "branches not found" change as they both solve the same problem of target branches not appearing when selecting a changeset to merge.

**Comment by CDuke** [comment]
Extension published - https://marketplace.visualstudio.com/items?itemName=KulikovDenis.AutoMergeforVisualStudio2022
